-- =============================================================================
-- HTMX Language Server (Currently Disabled)
-- =============================================================================
-- HTMX LSP support for modern web development with HTMX attributes
-- Note: Currently disabled pending stable htmx-lsp release
-- To enable: Uncomment the return statement and remove leading dashes
-- =============================================================================
-- return {
--     htmx = {
--         cmd = { "htmx-lsp", "--stdio" },
--         filetypes = { "htmx", "html" },
--         root_dir = vim.fs.root(0, {
--             "htmx.min.js",
--             "htmx.js",
--             "_includes/head.html",
--             "_includes/header.html",
--             "templates/",
--             "static/",
--         }),
--         settings = {
--             htmx = {},
--         },
--     },
-- }