return {
    {
        "catppuccin/nvim",
        name = "catppuccin",
        priority = 1000,
        config = function()
            require("catppuccin").setup({
                flavour = "mocha",
                background = {
                    dark = "mocha",
                },
                transparent_background = true,
                show_end_of_buffer = true,
                term_colors = false,
                dim_inactive = {
                    enabled = false,
                    shade = "dark",
                    percentage = 0.15,
                },
                no_italic = false,
                no_bold = false,
                no_underline = false,
                styles = {
                    comments = { "italic" },
                    conditionals = { "italic" },
                    loops = {},
                    functions = {},
                    keywords = {},
                    strings = {},
                    variables = {},
                    numbers = {},
                    booleans = {},
                    properties = {},
                    types = {},
                    operators = {},
                },
                lsp_styles = {
                    virtual_text = {
                        errors = { "italic" },
                        hints = { "italic" },
                        warnings = { "italic" },
                        information = { "italic" },
                        ok = { "italic" },
                    },
                    underlines = {
                        errors = { "underline" },
                        hints = { "underline" },
                        warnings = { "underline" },
                        information = { "underline" },
                        ok = { "underline" },
                    },
                    inlay_hints = {
                        background = true,
                    },
                },
                color_overrides = {
                    rosewater = "#f5e0dc",
                    flamingo = "#f2cdcd",
                    pink = "#f5c2e7",
                    mauve = "#cba6f7",
                    red = "#f38ba8",
                    maroon = "#eba0ac",
                    peach = "#fab387",
                    yellow = "#f9e2af",
                    green = "#a6e3a1",
                    teal = "#94e2d5",
                    sky = "#89dceb",
                    sapphire = "#74c7ec",
                    blue = "#89b4fa",
                    lavender = "#b4befe",
                    text = "#cdd6f4",
                    subtext1 = "#bac2de",
                    subtext0 = "#a6adc8",
                    overlay2 = "#9399b2",
                    overlay1 = "#7f849c",
                    overlay0 = "#6c7086",
                    surface2 = "#585b70",
                    surface1 = "#45475a",
                    surface0 = "#313244",
                    base = "#1e1e2e",
                    mantle = "#181825",
                    crust = "#11111b",
                },
                custom_highlights = {
                    LineNr = { fg = "#6c7086" },
                    Visual = { bg = "#45475a" },
                    Search = { bg = "#fab387", fg = "#1e1e2e" },
                    IncSearch = { bg = "#fab387", fg = "#1e1e2e" },
                    NormalFloat = { bg = "NONE" },
                    FloatBorder = { bg = "NONE", fg = "#6c7086" },
                    TelescopeBorder = { bg = "NONE", fg = "#6c7086" },
                    TelescopePromptBorder = { bg = "NONE", fg = "#6c7086" },
                    TelescopeResultsBorder = { bg = "NONE", fg = "#6c7086" },
                    TelescopePreviewBorder = { bg = "NONE", fg = "#6c7086" },
                    NvimTreeNormal = { bg = "NONE" },
                    NvimTreeVertSplit = { bg = "NONE", fg = "#313244" },
                    WinSeparator = { bg = "NONE", fg = "#313244" },
                    StatusLine = { bg = "NONE" },
                    StatusLineNC = { bg = "NONE", fg = "#6c7086" },
                    Pmenu = { bg = "NONE" },
                    PmenuSel = { bg = "#313244" },
                    PmenuSbar = { bg = "NONE" },
                    PmenuThumb = { bg = "#585b70" },
                    DiagnosticVirtualTextError = { fg = "#f38ba8", bg = "NONE" },
                    DiagnosticVirtualTextWarn = { fg = "#f9e2af", bg = "NONE" },
                    DiagnosticVirtualTextInfo = { fg = "#89dceb", bg = "NONE" },
                    DiagnosticVirtualTextHint = { fg = "#6c7086", bg = "NONE" },
                    DiagnosticError = { fg = "#f38ba8" },
                    DiagnosticWarn = { fg = "#f9e2af" },
                    DiagnosticInfo = { fg = "#89dceb" },
                    DiagnosticHint = { fg = "#6c7086" },
                    GitSignsAdd = { fg = "#a6e3a1" },
                    GitSignsChange = { fg = "#fab387" },
                    GitSignsDelete = { fg = "#f38ba8" },
                    Folded = { fg = "#6c7086", bg = "NONE" },
                    FoldColumn = { fg = "#6c7086", bg = "NONE" },
                    NormalDoc = { bg = "#1e1e2e" },
                },
                default_integrations = true,
                auto_integrations = true,
                integrations = {
                    cmp = true,
                    gitsigns = true,
                    mason = false,
                    notify = false,
                    mini = {
                        enabled = true,
                        indentscope_color = "",
                    },
                    blink_cmp = {
                        style = "none",
                    },
                },
            })

            vim.cmd.colorscheme "catppuccin"

            vim.api.nvim_create_autocmd("ColorScheme", {
                pattern = "catppuccin",
                callback = function()
                    vim.api.nvim_set_hl(0, "BlinkCmpMenu", { bg = "NONE" })
                    vim.api.nvim_set_hl(0, "BlinkCmpDoc", { bg = "NONE" })
                end,
            })
        end,
    },
}
